# Install Rest client extension to use this requests
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###
POST http://localhost:8889/predict
content-type: application/json

{
    "movie_id": "Movies/308374",
    "local": false,
    "extra_params": {
        "mdf": 100,
        "caption": "a basketball player jumping"
    }
}

