# Install Rest client extension to use this requests
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

###
POST http://localhost:8889/predict
content-type: application/json

{
    "movie_id": "Movies/114207740",
    "local": false,
    "extra_params": {
        "mdf": 26,
        "caption": "A man shoots himself in the leg with a pistol in front of other men in a street"
    }
}

